# Makefile for robotdowneyjr

all :
	ocamlopt -o main str.cmxa unix.cmxa Print.ml Board.mli Board.ml State.mli State.ml mustache.mli mustache.ml Greedy_bot.ml Baby_bot.mli Evaluations.mli Evaluations.ml Baby_bot.ml Test_bot.ml Manhattan_Bot.mli Manhattan_Bot.ml Minimax_bot.ml JohnRocker_bot.mli JohnRocker_bot.ml sixminuteab_bot.mli sixminuteab_bot.ml main.ml


clean :
	rm *.cmo
	rm *.cmi
