# Makefile for robotdowneyjr

all :
	ocamlc -o main str.cma Board.mli Board.ml State.mli State.ml Random_bot.mli Random_bot.ml Baby_bot.mli Baby_bot.ml Manhattan_Bot.mli Manhattan_Bot.ml main.ml

clean :
	rm *.cmo
	rm *.cmi
