# Makefile for robotdowneyjr

all :
	ocamlc -o main str.cma Unix.cma Board.mli Board.ml State.mli State.ml Random_bot.mli Random_bot.ml Baby_bot.mli Evaluations.mli Evaluations.ml Baby_bot.ml Test_bot.ml Manhattan_Bot.mli Manhattan_Bot.ml Minimax_bot.ml Round_two_bot.ml main.ml


clean :
	rm *.cmo
	rm *.cmi
